name: washouse_customer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  page_transition: ^2.0.9
  flutter_otp_text_field: ^1.1.1
  animated_bottom_navigation_bar: ^1.1.0+1
  json_annotation: ^4.8.0
  http: ^0.13.5
  flutter_rating_bar: ^4.0.1
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.5
  flutter_osm_plugin: ^0.53.1
  snippet_coder_utils: ^1.0.13
  google_sign_in: ^6.1.0
  awesome_snackbar_content: ^0.1.2
  flutter_otp: ^0.3.2
  anim_search_bar: ^2.0.3
  flutter_google_places: ^0.3.0
  skeletons: ^0.0.3
  flutter_typeahead: ^4.3.7
  roundcheckbox: ^2.0.5
  multi_select_flutter: ^4.1.3
  skeleton_animation: ^0.1.4
  intl: ^0.17.0-nullsafety.2
  shared_preferences: 
  percent_indicator: ^4.2.3
  otp_text_field: ^1.1.3
  image_picker: ^0.8.7+2
  flutter_datetime_picker: ^1.5.1
  flutter_cupertino_localizations: ^1.0.1
  dotted_line: ^3.1.0
  provider: ^6.0.5
  badges: ^3.0.3
  flutter_switch: ^0.3.2
  url_launcher: ^6.0.3
  flutter_secure_storage: ^8.0.0
  flutter_form_builder: ^7.8.0
  signalr_client:
  timelines: ^0.1.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  cloud_firestore: ^4.5.1
  fluttertoast: ^8.2.1
  cached_network_image: ^3.2.3
  firebase_storage: ^11.1.0
  photo_view: ^0.14.0
  flutter_local_notifications: ^13.0.0
  firebase_auth: ^4.4.1
  loading_animation_widget: ^1.2.0+4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  image_path: "assets/images/logo/washouse-favicon.png" 
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/category/
    - assets/images/category/outlined/
    - assets/images/empty/
    - assets/images/logo/
    - assets/images/order/
    - assets/images/post/
    - assets/images/profile/
    - assets/images/service/
    - assets/images/service_flow/
    - assets/images/shipping/
    - assets/images/started/
    - assets/images/sticker/
    - assets/images/transaction/