name: washouse_customer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  page_transition: ^2.0.9
  flutter_otp_text_field: ^1.1.1
  animated_bottom_navigation_bar: ^1.1.0+1
  json_annotation: ^4.8.0
  http: ^0.13.5
  flutter_rating_bar: ^4.0.1
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.5
  flutter_osm_plugin: ^0.53.1
  snippet_coder_utils: ^1.0.13
  google_sign_in: ^6.0.2
  awesome_snackbar_content: ^0.1.2
  flutter_otp: ^0.3.2
  anim_search_bar: ^2.0.3
  flutter_google_places: ^0.3.0
  skeletons: ^0.0.3
  flutter_typeahead: ^4.3.7
  roundcheckbox: ^2.0.5
  multi_select_flutter: ^4.1.3
  skeleton_animation: ^0.1.4
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  image_path: "assets/images/logo/washouse-favicon.png" 
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/category/
    - assets/images/category/outlined/
    - assets/images/logo/
    - assets/images/order/
    - assets/images/post/
    - assets/images/profile/
    - assets/images/service/
    - assets/images/service_flow/
    - assets/images/shipping/
    - assets/images/started/